---
name: Homebrew Package

"on":
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (e.g., 1.0.0)'
        required: true
        type: string
  repository_dispatch:
    types: [release-orchestrator]

jobs:
  update-homebrew:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update Homebrew formula
        run: |
          version="${{ github.event.release.tag_name ||
            github.event.inputs.version || github.event.client_payload.version }}"
          version="${version#v}"

          # Download binaries and calculate checksums
          echo "Downloading binaries to calculate checksums..."
          gh release download "v${version}" --repo sourcegraph/amp-cli --pattern "amp-darwin-arm64" --pattern "amp-darwin-x64" --pattern "amp-linux-arm64" --pattern "amp-linux-x64"

          # Calculate SHA256 checksums
          darwin_arm64_sha=$(shasum -a 256 amp-darwin-arm64 | cut -d' ' -f1)
          darwin_x64_sha=$(shasum -a 256 amp-darwin-x64 | cut -d' ' -f1)
          linux_arm64_sha=$(shasum -a 256 amp-linux-arm64 | cut -d' ' -f1)
          linux_x64_sha=$(shasum -a 256 amp-linux-x64 | cut -d' ' -f1)

          echo "Checksums calculated:"
          echo "Darwin ARM64: $darwin_arm64_sha"
          echo "Darwin x64: $darwin_x64_sha" 
          echo "Linux ARM64: $linux_arm64_sha"
          echo "Linux x64: $linux_x64_sha"

          # Update version and URLs in formula
          sed -i '' "s/version \".*\"/version \"$version\"/" Formula/amp.rb
          sed -i '' "s/v[0-9]\+\.[0-9]\+\.[0-9a-zA-Z\.\-]\+/v$version/g" Formula/amp.rb
          
          # Update SHA256 checksums
          sed -i '' "s/REPLACE_WITH_ACTUAL_SHA256/$darwin_arm64_sha/" Formula/amp.rb
          sed -i '' "s/REPLACE_WITH_ARM64_SHA256/$darwin_arm64_sha/" Formula/amp.rb
          sed -i '' "s/REPLACE_WITH_AMD64_SHA256/$darwin_x64_sha/" Formula/amp.rb
          sed -i '' "s/REPLACE_WITH_LINUX_ARM64_SHA256/$linux_arm64_sha/" Formula/amp.rb
          sed -i '' "s/REPLACE_WITH_LINUX_AMD64_SHA256/$linux_x64_sha/" Formula/amp.rb

          # Clean up downloaded files
          rm -f amp-darwin-arm64 amp-darwin-x64 amp-linux-arm64 amp-linux-x64

      - name: Commit updated formula
        run: |
          git config --local user.email "amp@ampcode.com"
          git config --local user.name "Amp"
          git add Formula/amp.rb
          git commit -m "Update Homebrew formula to ${{
            github.event.release.tag_name ||
            github.event.inputs.version || github.event.client_payload.version }}" || exit 0
          git push
