---
name: Homebrew Package

"on":
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (e.g., 1.0.0)'
        required: true
        type: string
  repository_dispatch:
    types: [release-orchestrator]

concurrency:
  group: homebrew-package
  cancel-in-progress: true

jobs:
  update-homebrew:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: main

      - name: Update Homebrew formula
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version="${{ github.event.release.tag_name ||
            github.event.inputs.version || github.event.client_payload.version }}"
          version="${version#v}"

          # Download binaries and calculate checksums
          echo "Downloading binaries to calculate checksums..."
          gh release download "v${version}" --repo sourcegraph/amp-packages \
            --pattern "amp-darwin-arm64" --pattern "amp-darwin-x64" \
            --pattern "amp-linux-arm64" --pattern "amp-linux-x64"

          # Calculate SHA256 checksums
          darwin_arm64_sha=$(shasum -a 256 amp-darwin-arm64 | cut -d' ' -f1)
          darwin_x64_sha=$(shasum -a 256 amp-darwin-x64 | cut -d' ' -f1)
          linux_arm64_sha=$(shasum -a 256 amp-linux-arm64 | cut -d' ' -f1)
          linux_x64_sha=$(shasum -a 256 amp-linux-x64 | cut -d' ' -f1)

          echo "Checksums calculated:"
          echo "Darwin ARM64: $darwin_arm64_sha"
          echo "Darwin x64: $darwin_x64_sha"
          echo "Linux ARM64: $linux_arm64_sha"
          echo "Linux x64: $linux_x64_sha"

          # Replace placeholders with actual values
          sed -i '' "s/VERSION_PLACEHOLDER/$version/g" Formula/amp.rb
          sed -i '' "s/REPLACE_WITH_DARWIN_ARM64_SHA256/$darwin_arm64_sha/g" Formula/amp.rb
          sed -i '' "s/REPLACE_WITH_DARWIN_AMD64_SHA256/$darwin_x64_sha/g" Formula/amp.rb
          sed -i '' "s/REPLACE_WITH_LINUX_ARM64_SHA256/$linux_arm64_sha/g" Formula/amp.rb
          sed -i '' "s/REPLACE_WITH_LINUX_AMD64_SHA256/$linux_x64_sha/g" Formula/amp.rb

          # Clean up downloaded files
          rm -f amp-darwin-arm64 amp-darwin-x64 amp-linux-arm64 amp-linux-x64

      - name: Commit updated formula
        run: |
          git config --local user.email "amp@ampcode.com"
          git config --local user.name "Amp"

          # Retry logic for concurrent workflow conflicts
          for i in {1..5}; do
            echo "Attempt $i/5 to commit and push changes"

            # Pull latest changes
            git pull origin main || true

            # Add and commit changes
            git add Formula/amp.rb
            if git commit -m "Update Homebrew formula to ${{
              github.event.release.tag_name ||
              github.event.inputs.version || github.event.client_payload.version }}"; then

              # Try to push
              if git push; then
                echo "Successfully pushed changes on attempt $i"
                exit 0
              else
                echo "Push failed on attempt $i, retrying..."
                sleep $((i * 2))
              fi
            else
              echo "No changes to commit on attempt $i"
              exit 0
            fi
          done

          echo "Failed to push after 5 attempts"
          exit 1
