---
name: Nix Package

"on":
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (e.g., 1.0.0)'
        required: true
        type: string
  repository_dispatch:
    types: [release-orchestrator]

jobs:
  update-nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update Nix flake
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version="${{ github.event.release.tag_name ||
            github.event.inputs.version || github.event.client_payload.version }}"
          version="${version#v}"

          # Download binaries and calculate checksums
          echo "Downloading binaries to calculate checksums..."
          gh release download "v${version}" --repo sourcegraph/amp-packages \
            --pattern "amp-linux-x64" --pattern "amp-linux-arm64" \
            --pattern "amp-darwin-x64" --pattern "amp-darwin-arm64"

          # Calculate SHA256 checksums
          linux_x64_sha=$(sha256sum amp-linux-x64 | cut -d' ' -f1)
          linux_arm64_sha=$(sha256sum amp-linux-arm64 | cut -d' ' -f1)
          darwin_x64_sha=$(sha256sum amp-darwin-x64 | cut -d' ' -f1)
          darwin_arm64_sha=$(sha256sum amp-darwin-arm64 | cut -d' ' -f1)

          echo "Checksums calculated:"
          echo "Linux x64: $linux_x64_sha"
          echo "Linux ARM64: $linux_arm64_sha"
          echo "Darwin x64: $darwin_x64_sha"
          echo "Darwin ARM64: $darwin_arm64_sha"

          # Update version in flake.nix
          sed -i "s/REPLACE_WITH_VERSION/$version/" flake.nix

          # Update SHA256 checksums
          sed -i "s/REPLACE_WITH_LINUX_X64_SHA256/$linux_x64_sha/" flake.nix
          sed -i "s/REPLACE_WITH_LINUX_ARM64_SHA256/$linux_arm64_sha/" flake.nix
          sed -i "s/REPLACE_WITH_DARWIN_X64_SHA256/$darwin_x64_sha/" flake.nix
          sed -i "s/REPLACE_WITH_DARWIN_ARM64_SHA256/$darwin_arm64_sha/" flake.nix

          # Clean up downloaded files
          rm -f amp-linux-x64 amp-linux-arm64 amp-darwin-x64 amp-darwin-arm64

      - name: Test Nix flake
        run: |
          nix flake check
          nix build .#amp

      - name: Commit updated flake
        run: |
          git config --local user.email "amp@ampcode.com"
          git config --local user.name "Amp"

          # Retry logic for concurrent workflow conflicts
          for i in {1..5}; do
            echo "Attempt $i/5 to commit and push changes"

            # Pull latest changes
            git pull origin main || true

            # Add and commit changes
            git add flake.nix
            if git commit -m "Update Nix flake to ${{
              github.event.release.tag_name ||
              github.event.inputs.version || github.event.client_payload.version }}"; then

              # Try to push
              if git push; then
                echo "Successfully pushed changes on attempt $i"
                exit 0
              else
                echo "Push failed on attempt $i, retrying..."
                sleep $((i * 2))
              fi
            else
              echo "No changes to commit on attempt $i"
              exit 0
            fi
          done

          echo "Failed to push after 5 attempts"
          exit 1
