---
name: Release Orchestrator

on:
  release:
    types: [published]

jobs:
  orchestrate-packaging:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for release assets to stabilize
        run: sleep 180  # Wait 3 minutes

      - name: Trigger AUR package update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-orchestrator
          client-payload: '{"workflow": "aur.yml", "version": "${{ github.event.release.tag_name }}"}'

      - name: Trigger Chocolatey package update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-orchestrator
          client-payload: '{"workflow": "chocolatey.yml", "version": "${{ github.event.release.tag_name }}"}'

      - name: Trigger Debian package build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-orchestrator
          client-payload: '{"workflow": "debian.yml", "version": "${{ github.event.release.tag_name }}"}'

      - name: Trigger Docker image build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-orchestrator
          client-payload: '{"workflow": "docker.yml", "version": "${{ github.event.release.tag_name }}"}'

      - name: Trigger Homebrew formula update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-orchestrator
          client-payload: '{"workflow": "homebrew.yml", "version": "${{ github.event.release.tag_name }}"}'

      - name: Trigger Nix package update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-orchestrator
          client-payload: '{"workflow": "nix.yml", "version": "${{ github.event.release.tag_name }}"}'

      - name: Trigger RPM package build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-orchestrator
          client-payload: '{"workflow": "rpm.yml", "version": "${{ github.event.release.tag_name }}"}'

      - name: Trigger Winget package update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-orchestrator
          client-payload: '{"workflow": "winget.yml", "version": "${{ github.event.release.tag_name }}"}'

  orchestrate-repositories:
    runs-on: ubuntu-latest
    needs: orchestrate-packaging
    steps:
      - name: Wait for package builds to complete
        run: sleep 300  # Wait 5 minutes for builds to complete

      - name: Trigger repository builds
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-orchestrator
          client-payload: '{"workflow": "repositories.yml", "version": "${{ github.event.release.tag_name }}"}'
